### ISSUE TITLE
file_directory

### ISSUE THREAD

**Issue by djengineerllc** [pohmelie/run-in-terminal#12]
Enhancement request:
It'd be nice if we could have an interpolation for file_directory.  If a certain folder is selected, then the file_directory would be the folder path.  If a file is selected, then the file_directory would be the path to the directory the file is in.

This would be useful for creating a menu item for opening the command prompt (in windows) to the directory selected in the tree.  Or, in my case, I'd like to use it to call "npm run build" on the command line at a selected directory.

**Comment by pohmelie** [comment]
Awesome idea. Not only tree view, but tabs too.

**Comment by pohmelie** [comment]
Oh, I think I missed your request, cause I made something different instead :laughing: 
You want to «Start terminal here» for custom folder in tree?

**Comment by pohmelie** [comment]
Does new feature of [0.5.0](https://github.com/pohmelie/run-in-terminal/blob/master/CHANGELOG.md) cover your request? If not, please, describe it more precisely.

**Comment by djengineerllc** [comment]
Yes, that is it.  It is working great!  Thanks pohmelie!  I had made a custom hack before, but then every time I would update, I'd loose my hack and it took me forever to figure out what I did to fix it, lol.  Thank you very much!

**Comment by djengineerllc** [comment]
Sorry for the delay, I was having a bit of an issue with my new Yubikey and 2fa with github.

**Comment by djengineerllc** [comment]
Yeah, your fix was actually even better that I was thinking.  Nice inclusion with the tabs!

**Comment by pohmelie** [comment]
@djengineerllc :wink:
