### ISSUE TITLE
Os termination signals. 

### ISSUE THREAD

**Issue by rustyoz** [pohmelie/run-in-terminal#13]
While using atom editor on Windows 10 and then opening cmd using the right click 'Start Terminal here"  cmd doesn't pass on or recognise Control-c to terminate a program, but manually starting a cmd terminal shows that the program does receive the termination signal.  

I don't think it is an issue with the package per se but incorrect parameters for executing cmd

**Comment by pohmelie** [comment]
Paste your settings for package here, please.

**Comment by rustyoz** [comment]
Don't worry just tried it again, must have been a transient problem with my computer
