### ISSUE TITLE
Terminal Doesn't Start

### ISSUE THREAD

**Issue by bobrocke** [pohmelie/run-in-terminal#3]
I must have my setting wrong because invoking a menu command does not launch a terminal session.

I've left everything at the default, expecting Mac OS X terminal.app to launch.

Are the defaults not appropriate on their own and must be supplied?

Does the "list of launchers by extension" need something besides the extension? Is it the full path to the desired terminal app?

**Comment by pohmelie** [comment]
I have no experience with mac os, but check console when running command.
View → Developer → Toggle developer tools
If there was some error you saw some debug information. Then you can post this information here.

**Comment by bobrocke** [comment]
There's an error:

```
run-in-terminal error when child_process.exec ->
cmd = your-favorite-terminal --foo --bar
error = Error: Command failed: /bin/sh -c your-favorite-terminal --foo --bar
/bin/sh: your-favorite-terminal: command not found

stdout = 
stderr = /bin/sh: your-favorite-terminal: command not found
```

That suggests the default setting won't work. So I set "list of launchers to: `/Applications/Admin/iTerm.app` and "terminal with arguments to: `/Applications/Admin/iTerm.app`. That configuration throws this error:

```
run-in-terminal error when child_process.exec ->
cmd = /Applications/Admin/iTerm.app
error = Error: Command failed: /bin/sh -c /Applications/Admin/iTerm.app
/bin/sh: /Applications/Admin/iTerm.app: is a directory

stdout = 
stderr = /bin/sh: /Applications/Admin/iTerm.app: is a directory
```

What do I need to fix in my configuration?

**Comment by pohmelie** [comment]
Launchers is only for determine which process to run inside your terminal, so it's later step. As I can see you get «is directory» error, so I think mac os have some console method to run such directory-package. I'm trying to run mac os in virtualbox, but boot time is pretty long (half an hour already and keep going).
Is «iTerm.app» the default terminal on mac os? Try to find comman which starts terminal from terminal %) and then you can just copy it to the «terminal with arguemnts»

**Comment by bobrocke** [comment]
The default terminal for Mac OS X is Terminal.app.

**Comment by pohmelie** [comment]
I think you should use «open -a /path/to/terminal.app» as said [here](http://stackoverflow.com/questions/11676007/how-do-you-open-a-new-mac-os-x-terminal-from-terminal-and-have-it-be-in-the-same)

**Comment by bobrocke** [comment]
That was it! Thanks for the extra research.
