### ISSUE TITLE
Launcher by extension doesn't work on Windows

### ISSUE THREAD

**Issue by dwellexity** [pohmelie/run-in-terminal#4]
I tried using launcher by extension on Windows and it doesn't work. Basically I wanted .py files to be run as 'python file.py' when I use 'start and run'.

**Comment by pohmelie** [comment]
My working configuration on Windows 7 is:
List of launchers by extension: ".py python {file_path}, .lua lua {file_path}"
Terminal with arguments: "start /D {working_directory} C:\Windows\System32\cmd.exe /u"
Terminal execution argument: "/k"
What is yours?

**Comment by dwellexity** [comment]
I had no idea what to put in terminal execution argument. It works now.
Thanks. 
And you should put an example of terminal execution argument in readme.

**Comment by pohmelie** [comment]
Terminal execution argument is platform specific (so do other). So you should read documentation for windows "start" and "cmd" commands. By the way, examples already in readme :ok_hand:
