### ISSUE TITLE
Paths including spaces don't work on windows

### ISSUE THREAD

**Issue by LeoVerto** [pohmelie/run-in-terminal#7]
Basically when any variable like `{working_directory}` contains a space, cmd interprets is as two seperate commands and it won't run.

The workaround I've found for this is to add quotation marks around variables.
For example `.py py {file_path}` becomes `.py py "{file_path}"`.

I would have submitted a PR to fix this, but I don't think this workaround would work on other platforms.

**Comment by pohmelie** [comment]
Thanks for issue. I think it will work on other platforms too, but I can't test it right now. I will test it after 10 days (cause I'm afk :grin:). I don't really know what is better: change readme and tell user that quotation is good idea, or just do autoquote?
